version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    hostname: frontend.docker
  backend:
    build: ./backend
    ports:
      - 8080:8080
    volumes:
      - static:/app/uploads
    hostname: backend.docker
  caddy:
    build: ./caddy
    ports:
      - 80:80
      - 443:443
volumes:
  static:
