version: '3.8'
services:
  frontend:
    build: ./frontend
    hostname: frontend.docker
    restart: unless-stopped
  backend:
    depends_on:
      postgres:
        condition: service_healthy
    build: ./backend
    volumes:
      - static:/app/uploads
      - backup:/app/backup
    hostname: backend.docker
    restart: unless-stopped
  caddy:
    build: ./caddy
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
      - caddy_data:/data
      - caddy_config:/config
  postgres:
    build: ./postgres
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    env_file:
      - ./postgres/postgres.env
    hostname: database.docker
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker"]
      interval: 1s
      timeout: 5s
      retries: 30
    restart: unless-stopped
  pgadmin:
    image: dpage/pgadmin4:latest
    hostname: pgadmin.docker
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 8080:80
    env_file:
      - ./postgres/pgadmin.env
    restart: unless-stopped
volumes:
  static:
  backup:
  pgdata:
  caddy_data:
  caddy_config: