version: '3.8'
services:
  frontend:
    build: ./frontend
    hostname: frontend.docker
  backend:
    depends_on:
      - postgres
    build: ./backend
    volumes:
      - static:/app/uploads
      - backup:/app/backup
    hostname: backend.docker
  caddy:
    build: ./caddy
    ports:
      - 80:80
      - 443:443
  postgres:
    image: postgres:alpine3.17
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    env_file:
      - ./scripts/postgres.env
    hostname: database.docker
    ports:
      - 5432:5432
volumes:
  static:
  backup:
  pgdata: