version: '3.8'
services:
  frontend:
    build: ./frontend
    hostname: frontend.docker
  backend:
    depends_on:
      postgres:
        condition: service_healthy
    build: ./backend
    volumes:
      - static:/app/uploads
      - backup:/app/backup
    hostname: backend.docker
  caddy:
    build: ./caddy
    ports:
      - 80:80
      - 443:443
  postgres:
    build: ./postgres
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    env_file:
      - ./postgres/postgres.env
    hostname: database.docker
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker"]
      interval: 1s
      timeout: 5s
      retries: 30
  metabase:
    image: metabase/metabase:latest
    hostname: metabase.docker
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 3000:3000
volumes:
  static:
  backup:
  pgdata: